apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062502824765:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CAHL2O07EJ5S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::062502824765:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T15:37:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1561"
  uid: af28eef1-4ca7-4af6-9665-b42886e1cb17
